This project is a friendly fork of the official Git completion
(`contrib/completion`) and prompt scripts for Bash, Zsh, and possibly other
shells.

Most Git developers use the Bash shell, for which the completion scripts work
rather well, however, Zsh is typically neglected. I've sent many patches to fix
the issues, many have been merged, but in the last years all my patches have
been ignored, thus the need for a canonical location of a good, working Zsh
completion.

There are advantages for Bash users too. Currently the scripts under `contrib`
are tied to the specific Git version, for example
the completion scripts of version v2.22
(https://git.kernel.org/pub/scm/git/git.git/plain/contrib/completion/git-completion.bash?h=v2.22.0[git-completion.bash])
don't work with older versions of Git (e.g. v2.16); the ones in
this project do.

With `git-completion` you can be sure you are using the latest completion that
works in both shells, and any Git version.

This is a sister project of the
https://github.com/robbyrussell/oh-my-zsh/wiki/Plugins#gitfast[oh-my-zsh
gitfast] plugin (that I also maintain), which has similar needs.

== Installation ==

Simply run `make install`, then, depending on your shell:

=== Bash ===
==== Completion ====

If you are using bash-completion you don't have to do anything else, but if
not; you simply need to source this file in your `~/.bashrc`:

  source ~/.local/share/bash-completion/completions/git

==== Prompt ====

Source the prompt file in your `~/.bashrc`:

  source ~/.local/share/git-completion/prompt.sh

Change your PS1 (e.g. in `~/.bashrc`) to something that includes
`$(__git_ps1)`, for example:

  PS1='\h \w$(__git_ps1 "[%s]") \$ '

If you want to use colors, or a faster prompt, you need to use the
`PROMPT_COMMAND` mode instead:

  GIT_PS1_SHOWCOLORHINTS=1
  PROMPT_COMMAND='__git_ps1 "\h \w" " \\\$ " "[%s]"'

In this mode the `__git_ps1` function will override the PS1 variable each time
you are in a prompt.

=== Zsh ===
==== Completion ====

Edit `~/.zshrc` and add the following:

  fpath=(~/.local/share/git-completion/zsh $fpath)

==== Prompt ====

Source the prompt file in your `~/.zshrc`:

  source ~/.local/share/git-completion/prompt.sh

You need to add `$(__git_ps1)` to your PS1, for exmple in `~/.zshrc`:

  setopt PROMPT_SUBST
  PS1='%m %~$(__git_ps1 "[%s]") %# '

If you want colors, simply add:

  GIT_PS1_SHOWCOLORHINTS=1

== Configuration ==

By default aliases and custom commands are automatically handled, but you might
have custom functions, for example:

  glm() { git log ^master ${@:-HEAD} ; }

There's no way for the completion to do the sensible thing here, unless you
manually configure it:

=== Bash ===

You have to use the internal `__git_complete` function:

  __git_complete glm _git_log

If you want a shortcut for the git command itself:

  __git_complete g __git_main

=== Zsh ===

You can use Zsh's `compdef`:

  compdef _git glm=git_log

== Improvements from upstream ==

This is a short list of the benefits you get:

* Easier installation
* Zsh: doesn't add extra spaces
* Zsh: colors work without PC
* Zsh: custom aliases can be configured
* Zsh: fixed many --options and --no-options
* Zsh: don't mess with bashcomp
* Zsh: other cosmetic improvements
* Bash: works in older versions of Git
* Bash: works outside of a Git repository
