#!/usr/bin/env ruby

def title(text)
  puts [nil, text, '-' * text.size]
end

ENV['PATH'] = '/opt/git/bin:/usr/bin'

$skip = [
  'bisect--helper',
  'env--helper',
  'submodule--helper',
  'checkout--worker',
  'credential-cache--daemon',
  'fsmonitor--daemon',
  'difftool--helper',
  'add--interactive',
  'gui--askpass',
  'sh-i18n--envsubst',
  'upload-archive--writer',
  'web--browse',
  'rebase--helper',
]

title 'Options'

cmds = %x[git --list-cmds=parseopt].split(' ')

cmds = cmds - $skip

cmds.each do |cmd|
  opts = %x[git #{cmd} --git-completion-helper].split(' ')
  puts "__gitcomp_builtin_%s_default=\"%s\"" % [cmd.gsub('-', '_'), opts.join(' ')]
end

puts "__gitcomp_builtin_%s_default=\"%s\"" % ['send_email', %x[git send-email --git-completion-helper].split(' ').sort.join(' ')]

title 'Commands'

groups = %w[list-complete list-guide list-mainporcelain main others parseopt]

groups.each do |group|
  cmds = group == 'others' ? [] : %x[git --list-cmds=#{group}].split(' ') - $skip
  puts "__git_cmds[%s]=\"%s\"" % [group, cmds.join(' ')]
end
