#!/usr/bin/env ruby

def title(text)
  puts [nil, text, '-' * text.size]
end

ENV['PATH'] = '/opt/git/bin:/usr/bin'

title 'Options'

cmds = %x[git --list-cmds=parseopt].split(" ")
cmds << 'send-email'

cmds.each do |cmd|
  opts = %x[git #{cmd} --git-completion-helper].split("\n")
  puts "__gitcomp_builtin_%s_default=\"%s\"" % [cmd.gsub('-', '_'), opts.join(' ')]
end

title 'Commands'

groups=%w[list-complete list-guide list-mainporcelain main others parseopt]

groups.each do |group|
  cmds = %x[git --list-cmds=#{group}].split("\n")
  puts "__git_cmds[%s]=\"%s\"" % [group, cmds.join(' ')]
end
