#!/bin/sh

url="https://git.kernel.org/pub/scm/git/git.git/plain"
version="2.40.0"

git stash push -q &&
git checkout -q upstream &&
curl -s -o src/_git "${url}/contrib/completion/git-completion.zsh?h=v${version}" &&
curl -s -o src/git-completion.bash "${url}/contrib/completion/git-completion.bash?h=v${version}" &&
curl -s -o src/git-prompt.sh "${url}/contrib/completion/git-prompt.sh?h=v${version}" &&
curl -s -o t/completion.t "${url}/t/t9902-completion.sh?h=v${version}" &&
curl -s -o t/prompt.t "${url}/t/t9903-bash-prompt.sh?h=v${version}" &&
git commit -q -a -s -m "Update to upstream v${version}" &&
git checkout -q - &&
git stash pop -q &&
echo "Updated to v${version}"
